language: objective-c
osx_image: xcode13.4
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - PROJECT=libcmark_gfm.xcodeproj
  - IOS_FRAMEWORK_SCHEME="libcmark_gfm-iOS"
  - MACOS_FRAMEWORK_SCHEME="libcmark_gfm-macOS"
  - TVOS_FRAMEWORK_SCHEME="libcmark_gfm-tvOS"
  - WATCHOS_FRAMEWORK_SCHEME="libcmark_gfm-watchOS"
  - IOS_SDK=iphonesimulator15.5
  - MACOS_SDK=macosx12.3
  - TVOS_SDK=appletvsimulator15.4
  - WATCHOS_SDK=watchsimulator8.5
  matrix:
    - DESTINATION="OS=8.5,name=Apple Watch Series 7 - 45mm"   SCHEME="$WATCHOS_FRAMEWORK_SCHEME" SDK="$WATCHOS_SDK" RUN_TESTS="NO"  POD_LINT="NO"

    - DESTINATION="OS=15.4,name=Apple TV 4K (2nd generation)" SCHEME="$TVOS_FRAMEWORK_SCHEME"    SDK="$TVOS_SDK"    RUN_TESTS="NO" POD_LINT="NO"

    - DESTINATION="arch=x86_64"                               SCHEME="$MACOS_FRAMEWORK_SCHEME"   SDK="$MACOS_SDK"   RUN_TESTS="NO" POD_LINT="NO"

    - DESTINATION="OS=15.5,name=iPhone 13 Pro Max"            SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="NO" POD_LINT="YES"

before_install:
  - gem install cocoapods --pre --no-document --quiet
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks

  # Build Framework in Debug and Run Tests if specified
  - if [ $RUN_TESTS == "YES" ]; then
      xcodebuild -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty;
    else
      xcodebuild -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty;
    fi

  # Build Framework in Release and Run Tests if specified
  - if [ $RUN_TESTS == "YES" ]; then
      xcodebuild -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty;
    else
      xcodebuild -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO build | xcpretty;
    fi

  # Run `pod lib lint` if specified
  - if [ $POD_LINT == "YES" ]; then
      pod lib lint --allow-warnings --skip-tests;
    fi
